### ISSUE TITLE
Support BagIt v1.0

### ISSUE THREAD

**Issue by vpeil** [LibreCat/Catmandu-BagIt#10]
https://tools.ietf.org/html/rfc8493

**Comment by Bolkun** [comment]
It's already 2020, but unfortunately Catmandu-BagIt Library still supports only 0.97 version. Is there a hope for 1.0 release ?

**Comment by phochste** [comment]
@bolkun Yes, we will work in 1.0 release. Stay tuned.

**Comment by Bolkun** [comment]
@phochste It would be great if you could tell me a release date, so I could test it.

**Comment by phochste** [comment]
version 0.250 is on its way to cpan
