### ISSUE TITLE
self-cleanup

### ISSUE THREAD

**Issue by vpeil** [LibreCat/Catmandu-BagIt#3]
By running the nice example script https://github.com/LibreCat/Catmandu-BagIt/blob/master/examples/oai2bagit.sh one issue occurs to me: Files are fetched into /tmp, after the bag is created the files remain in the /tmp-directory and one runs out of disk space..

can we delete the tempfile after the bag has been created?

**Comment by phochste** [comment]
Can you provide some details on the OS? The code is self cleaning tempfile() is used that should automatically delete the fetched files after each record.

**Comment by vpeil** [comment]
I'm on debian, but had the same issue on openSuse server...

on debian:

```
$ uname -a
Linux ubi 4.2.0-1-amd64 #1 SMP Debian 4.2.6-3 (2015-12-06) x86_64 GNU/Linux
```
