### ISSUE TITLE
support key "files" in Catmandu::Exporter::BagIt

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu-BagIt#7]
Now the Catmandu::Exporter::BagIt creates bagits from files that are referenced by url ( using the "fetch" option in bagit ).

Shouldn't there be also a key "files" for local files?

```
$exporter->add({
  _id => "/home/njfranck/bagit1",
  files => [
     "/tmp/file1.tif" => "data/file1.tif",
     "/tmp/file2.tif" => "data/file2.tif"
  ]
});
```

I"ll send a pull request when ok.

**Comment by nicolasfranck** [comment]
If you provide a file url:

```
$exporter->add({
  _id => "/home/njfranck/bagit1",
  fetch => [
    {
        "file:///tmp/test.tif" => "data/test.tif"
    }
  }
);
```

the file is downloaded, but cannot be mirrored:
```
failed to mirror file:///tmp/test.tif to /var/folders/bw/97qdtwtx4r5cyk7567bm1jj00000gn/T/RYe3HYyJXR.tmp : 304 GET /tmp/test.tif
```

**Comment by phochste** [comment]
Indeed, this is not yet supported. It would be a cool feature to be able to fetch also local files using the 'fetch' mechanism
